### ISSUE TITLE
ImportError: /opt/rocm/lib/librccl.so: undefined symbol: hipExtLaunchMultiKernelMultiDevice

### ISSUE THREAD

**Issue by MatPoliquin** [ROCmSoftwarePlatform/rccl#109]
After installing rccl I get this error when I import tensorflow in python:
/rocm/lib/librccl.so: undefined symbol: hipExtLaunchMultiKernelMultiDevice

I installed rccl by creating a deb with the provided install script:
 ./install.sh -p
sudo dpkg -i rccl-2.6.0-1969e89-Linux.deb

versions:
tensorflow-rocm 1.14
Ubuntu 18.10

**Comment by MatPoliquin** [comment]
I have tested with version 1.13 and it works

**Comment by wenkaidu** [comment]
RCCL master branch is for active development. We can only guarantee successful build and functionally with latest roc-master. Please use RCCL branch that matches ROCm release you are currently using. For example, if you installed ROCm 2.7 release, please use RCCL from this branch: https://github.com/ROCmSoftwarePlatform/rccl/tree/master-rocm-2.7
