### ISSUE TITLE
I can't run this demo.

### ISSUE THREAD

**Issue by BaldStrong** [ROCmSoftwarePlatform/rccl#323]
- CentOS 7.6
- ROCm2.9
- RCCL(NCCL) version 2.4.8

**The demo code is as follows:**
```C
#include "hip/hip_runtime.h"
#include <stdio.h>
#include <malloc.h>
#include <stdlib.h>
#include "rccl.h"

#define HIP_CHECK(command){  \
	hipError_t status = command; \
	if(status != hipSuccess){ \
		fprintf(stderr,"Error: HIP reports:%s\n", hipGetErrorString(status)); \
	} \
}

#define NCCLCHECK(cmd) do{   \
    ncclResult_t r=cmd;    \
    if(r!=ncclSuccess){     \
        printf("Failed, NCCL error %s:%d '%s'\n",__FILE__,__LINE__,ncclGetErrorString(r));   \
        exit(1);    \
    }                        \
} while(0)

int main(int argc, char** argv) {
    printf("begin run main...\n");

    ncclComm_t comms[1];

    //manageing 1 devices
    int nDev = 2;
    int size = 32;
    int devs[2] = { 0,1 };

    //allocating and initializing device buffers
    float** sendbuff = (float**)malloc(nDev * sizeof(float*));
    float** recvbuff = (float**)malloc(nDev * sizeof(float*));

    hipStream_t* s = (hipStream_t*)malloc(nDev * sizeof(hipStream_t));

    for (int i = 0;i < nDev;i++) {
        printf("cudaSetdevice..\n");
        HIP_CHECK(hipSetDevice(i));
        HIP_CHECK(hipMalloc(sendbuff + i, size * sizeof(float)));
        HIP_CHECK(hipMalloc(recvbuff + i, size * sizeof(float)));
        HIP_CHECK(hipMemset(sendbuff[i], 1, size * sizeof(float)));
        HIP_CHECK(hipMemset(recvbuff[i], 0, size * sizeof(float)));
        float* h_arr;
        h_arr = (float*)malloc(size * sizeof(float));
        for (int i = 0; i < size; ++i)
            h_arr[i] = i; // Or other values
        HIP_CHECK(hipMemcpy(sendbuff[i], h_arr, size * sizeof(float), hipMemcpyHostToDevice));
        //CUDACHECK(hipStreamCreate(s+i));
    }
    //initilzing NCCL
    NCCLCHECK(ncclCommInitAll(comms, nDev, devs));
    //calling NCCL communication API. Group API is required when using
    //multiple devices per thread
    NCCLCHECK(ncclGroupStart());

    for (int i = 0; i < nDev; ++i)
        //NCCLCHECK(ncclAllReduce((const void*)sendbuff[i], (void*)recvbuff[i], size, ncclFloat, ncclSum, comms[i], s[i]));
        NCCLCHECK(ncclReduce((const void *)sendbuff[i], (void*)recvbuff[i],size,ncclFloat, ncclSum, 0,comms[i], s[i]));


    NCCLCHECK(ncclGroupEnd());
    printf("\n ncclGroupEnd..\n");
    //synchronizing on CUDA streams to wait for completion of NCCL operation
    for (int i = 0; i < nDev; ++i) {
        HIP_CHECK(hipSetDevice(i));
        HIP_CHECK(hipStreamSynchronize(s[i]));
    }
    for (int i = 0; i < nDev; ++i) {
        HIP_CHECK(hipSetDevice(i));
        float* recvCPU = (float*)malloc(size * sizeof(float));
        HIP_CHECK(hipMemcpy(recvCPU, recvbuff[i], sizeof(float) * size, hipMemcpyDeviceToHost));
        printf("End Reduce Dev is %d of process, RecvBUf is %f,%f,%f,%f\n", i, recvCPU[0], recvCPU[1], recvCPU[2], recvCPU[3]);

    }
    //free device buffers
    for (int i = 0; i < nDev; ++i) {
        HIP_CHECK(hipSetDevice(i));
        HIP_CHECK(hipFree(sendbuff[i]));
        HIP_CHECK(hipFree(recvbuff[i]));
    }

    //finalizing NCCL
    for (int i = 0; i < nDev; ++i)
        ncclCommDestroy(comms[i]);

    printf("Success \n");
    return 0;
}
```

**Compile and run as follows:**
```bash
hipcc -l rccl demo.cpp
NCCL_DEBUG=INFO ./a.out
```

**The screen output is as follows:**
```bash
begin run main...
cudaSetdevice..
cudaSetdevice..
a03r2n12:45142:45142 [1] NCCL INFO Bootstrap : Using [0]ib0:11.1.3.33<0>
a03r2n12:45142:45142 [1] NCCL INFO NET/Plugin : No plugin found (libnccl-net.so).
a03r2n12:45142:45142 [1] NCCL INFO NET/IB : Using [0]mlx5_3:1/IB [1]mlx5_2:1/IB [2]mlx5_1:1/IB [3]mlx5_0:1/IB ; OOB ib0:11.1.3.33<0>
NCCL version 2.4.8+hip
a03r2n12:45142:45142 [1] NCCL INFO nranks 2
a03r2n12:45142:45142 [0] NCCL INFO Setting affinity for GPU 0 to 01
a03r2n12:45142:45142 [1] NCCL INFO 0 -> 1: link type QPI hops 2
a03r2n12:45142:45142 [1] NCCL INFO 1 -> 0: link type QPI hops 2
a03r2n12:45142:45142 [0] NCCL INFO Duplicating rings to 2 per user request.
a03r2n12:45142:45142 [1] NCCL INFO Using 256 threads, Min Comp Cap 3, Trees disabled
a03r2n12:45142:45142 [1] NCCL INFO Channel 00 :    0   1
a03r2n12:45142:45142 [1] NCCL INFO Channel 01 :    0   1
a03r2n12:45142:45142 [0] NCCL INFO Setting affinity for GPU 0 to 01
a03r2n12:45142:45142 [0] NCCL INFO Setting affinity for GPU 0 to 01
a03r2n12:45142:45142 [0] NCCL INFO Ring 00 : 0[0] -> 1[1] via direct shared memory
a03r2n12:45142:45142 [1] NCCL INFO Setting affinity for GPU 1 to 0100
a03r2n12:45142:45142 [1] NCCL INFO Setting affinity for GPU 1 to 0100
a03r2n12:45142:45142 [1] NCCL INFO Ring 00 : 1[1] -> 0[0] via direct shared memory
a03r2n12:45142:45142 [0] NCCL INFO Setting affinity for GPU 0 to 01
a03r2n12:45142:45142 [0] NCCL INFO Setting affinity for GPU 0 to 01
a03r2n12:45142:45142 [0] NCCL INFO Ring 01 : 0[0] -> 1[1] via direct shared memory
a03r2n12:45142:45142 [1] NCCL INFO Setting affinity for GPU 1 to 0100
a03r2n12:45142:45142 [1] NCCL INFO Setting affinity for GPU 1 to 0100
a03r2n12:45142:45142 [1] NCCL INFO Ring 01 : 1[1] -> 0[0] via direct shared memory
terminate called after throwing an instance of 'std::system_error’
  what():  Invalid argument
Aborted
```

**When I run it for the third time, there will be no errors, but the program will hang. I tried the ROCm3.3, and it still has this problem. Changing _ncclReduce_ to other communication functions has no effect.**

**Comment by gilbertlee-amd** [comment]
Would you be able to try it with a newer version of ROCm?  
You can find the latest version (v4.0.1) here: https://github.com/RadeonOpenCompute/ROCm

Note: AMD ROCm release v3.3 or prior releases are not fully compatible with AMD ROCm v3.5 and higher versions. You must perform a fresh ROCm installation if you want to upgrade from AMD ROCm v3.3 or older to 3.5 or higher versions and vice-versa.

**Comment by gilbertlee-amd** [comment]
Actually, it looks like you might have too few comm.

Could you try changing ncclComm_t comms[1] to comms[2]?
You will require one communicator per device.

**Comment by BaldStrong** [comment]
I found the problem. Because I commented out the code to create the hipStream, which caused this very low-level error.
`//CUDACHECK(hipStreamCreate(s+i));`

**Comment by doctorcolinsmith** [comment]
Thanks @BaldStrong for confirming that you fixed the problem.  Please reach out again if you encounter more issues.
