### ISSUE TITLE
Rccl error, unhandled system error

### ISSUE THREAD

**Issue by qili93** [ROCmSoftwarePlatform/rccl#328]
OS: centos:7.8.2003
 -- HIP version: 4.0.20496-4f163c68
 -- HIP_CLANG_PATH: /opt/rocm/llvm/bin
 -- miopen version: 2.9.0.8252-26-64506314
 -- rocblas version: 2.32.0.2844-cc18d25f
 -- hiprand version: 2.10.6.746-26-3932e69
 -- rocrand version: 2.10.6.746-26-3932e69
 -- rccl version: 2.7.8.492-26-e87f28e
 -- rocthrust version: 2.10.6.809-26-9041d6c
 -- hipcub version: 2.10.5.207-26-7bda2e4
 -- rocprim version: 2.10.5.1102-26-9d47868
 -- hipsparse version: 1.9.4.307-26-39bdb97
 -- rocsparse version: 1.18.0.863-26-296dfe7
 -- rocfft version: 1.0.8.966-26-2d35fd6
 -- HIP library name: amdhip64
 -- ROCM_HIPRTC_LIB: /opt/rocm/hip/lib/libamdhip64.so
 -- Current RCCL header is /opt/rocm-4.0.1/rccl/include/rccl.h. Current RCCL version is v2708. 

Running two containers in same node as following docker run command，`rocm-smi` is able to find 2 GPUs in each container, and these two container is able to ping  each ips and logon by ssh port 22 without passwd after configure.

```bash
# node 1
docker run -dit --name liqi-rocm1 -v /home/liqi27/host1:/workspace \
     --shm-size=128G -v /Data:/Data --network=test-net -p 2222:22 \
     --device=/dev/kfd --device=/dev/dri/renderD128 --device=/dev/dri/renderD129 --group-add video \
     --cap-add=SYS_PTRACE --security-opt seccomp=unconfined \
     qili93/paddle:latest-centos-dev-rocm401 /bin/bash \
     -c "/usr/sbin/sshd -D"

# node2
docker run -dit --name liqi-rocm2 -v /home/liqi27/host2:/workspace \
     --shm-size=128G -v /Data:/Data --network=test-net -p 3333:22 \
     --device=/dev/kfd --device=/dev/dri/renderD130 --device=/dev/dri/renderD131 --group-add video \
     --cap-add=SYS_PTRACE --security-opt seccomp=unconfined \
     qili93/paddle:latest-centos-dev-rocm401 /bin/bash \
     -c "/usr/sbin/sshd -D"
```

Run distributed training with `export NCCL_DEBUG=INFO`, and found error log as following:

```bash
/opt/conda/lib/python3.7/site-packages/paddle/distributed/fleet/base/fleet_base.py:632: UserWarning: It is recommended to use DistributedStrategy in fleet.init(). The strategy here is only for compatibility. If the strategy in fleet.distributed_optimizer() is not None, then it will overwrite the DistributedStrategy in fleet.init(), which will take effect in distributed training.
  "It is recommended to use DistributedStrategy "
W0315 11:13:58.839251   578 device_context.cc:368] Please NOTE: device: 1, GPU Compute Capability: 90.0, Driver API Version: 321.0, Runtime API Version: 3.1
W0315 11:13:58.839298   578 device_context.cc:381] device: 1, MIOpen Version: 2.9.0
I0315 11:13:59.260716   578 gen_comm_id_helper.cc:179] Server listening on: 10.0.1.17:6071 successful.
/opt/conda/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py:89: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if isinstance(slot[0], (np.ndarray, np.bool, numbers.Number)):
/opt/conda/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py:89: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if isinstance(slot[0], (np.ndarray, np.bool, numbers.Number)):
/opt/conda/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py:89: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if isinstance(slot[0], (np.ndarray, np.bool, numbers.Number)):
/opt/conda/lib/python3.7/site-packages/paddle/fluid/dataloader/dataloader_iter.py:89: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  if isinstance(slot[0], (np.ndarray, np.bool, numbers.Number)):
526432f383cd:578:578 [1] NCCL INFO Bootstrap : Using [0]eth0:10.0.1.17<0> [1]eth1:172.17.0.3<0>
526432f383cd:578:578 [1] NCCL INFO NET/Plugin : No plugin found (librccl-net.so), using internal implementation

526432f383cd:578:578 [1] /root/driver/rccl/src/misc/ibvwrap.cc:63 NCCL WARN Failed to open libibverbs.so[.1]
526432f383cd:578:578 [1] NCCL INFO NET/Socket : Using [0]eth0:10.0.1.17<0> [1]eth1:172.17.0.3<0>
526432f383cd:578:578 [1] NCCL INFO Using network Socket
526432f383cd:578:659 [1] NCCL INFO RCCL AllToAll(v)/Scatter/Gather kernels enabled
526432f383cd:578:659 [1] NCCL INFO threadThresholds 8/8/64 | 32/8/64 | 8/8/64
526432f383cd:578:659 [1] NCCL INFO Trees [0] -1/-1/-1->1->0|0->1->-1/-1/-1 [1] -1/-1/-1->1->0|0->1->-1/-1/-1 [2] -1/-1/-1->1->0|0->1->-1/-1/-1 [3] -1/-1/-1->1->0|0->1->-1/-1/-1
526432f383cd:578:659 [1] NCCL INFO Setting affinity for GPU 1 to ff00
526432f383cd:578:659 [1] NCCL INFO Channel 00 : 1[26000] -> 2[43000] [send] via NET/Socket/0/MEM1
526432f383cd:578:659 [1] NCCL INFO Channel 00 : 1[26000] -> 0[4000] via direct shared memory
526432f383cd:578:659 [1] NCCL INFO Channel 01 : 1[26000] -> 2[43000] [send] via NET/Socket/1/MEM1
526432f383cd:578:659 [1] NCCL INFO Call to connect returned Connection timed out, retrying
526432f383cd:578:659 [1] NCCL INFO Call to connect returned Connection timed out, retrying

526432f383cd:578:659 [1] /root/driver/rccl/src/include/socket.h:408 NCCL WARN Connect to 172.17.0.4<46303> failed : Connection timed out
526432f383cd:578:659 [1] NCCL INFO /root/driver/rccl/src/transport/net_socket.cc:314 -> 2
526432f383cd:578:659 [1] NCCL INFO /root/driver/rccl/src/include/net.h:22 -> 2
526432f383cd:578:659 [1] NCCL INFO /root/driver/rccl/src/transport/net.cc:175 -> 2
526432f383cd:578:659 [1] NCCL INFO /root/driver/rccl/src/transport.cc:69 -> 2
526432f383cd:578:659 [1] NCCL INFO /root/driver/rccl/src/init.cc:922 -> 2
526432f383cd:578:659 [1] NCCL INFO /root/driver/rccl/src/init.cc:1038 -> 2
526432f383cd:578:659 [1] NCCL INFO /root/driver/rccl/src/group.cc:74 -> 2 [Async thread]
Traceback (most recent call last):
  File "tools/static/train.py", line 191, in <module>
    main(args)
  File "tools/static/train.py", line 163, in main
    lr_scheduler)
  File "/workspace/PaddleClas/tools/static/program.py", line 538, in run
    fetch_list=fetch_list)
  File "/opt/conda/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1110, in run
    six.reraise(*sys.exc_info())
  File "/opt/conda/lib/python3.7/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/conda/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1108, in run
    return_merged=return_merged)
  File "/opt/conda/lib/python3.7/site-packages/paddle/fluid/executor.py", line 1217, in _run_impl
    program._graph._compile(scope, self.place)
  File "/opt/conda/lib/python3.7/site-packages/paddle/fluid/compiler.py", line 465, in _compile
    use_device=use_device, scope=self._scope, places=self._places)
  File "/opt/conda/lib/python3.7/site-packages/paddle/fluid/compiler.py", line 415, in _compile_data_parallel
    self._exec_strategy, self._build_strategy, self._graph)
OSError: (External)  Rccl error, unhandled system error  (at /workspace/Github-qili93/Paddle/paddle/fluid/platform/nccl_helper.h:77)
```

The code around `nccl_helper.h:77` is here:

https://github.com/PaddlePaddle/Paddle/blob/develop/paddle/fluid/platform/nccl_helper.h#L77

**Comment by qili93** [comment]
BTW, also tried two nodes and connecting network by docker swarm, and same issue as above. Any help?

**Comment by qili93** [comment]
Close this issue, problem resolved after setting "export NCCL_SOCKET_IFNAME=eth0"
