### ISSUE TITLE
RCCL sample program crashes with `Memory access fault by GPU node-1` for 2 GPUs machine 

### ISSUE THREAD

**Issue by syoyo** [ROCmSoftwarePlatform/rccl#59]
OS: Ubuntu 18.04, 16.04. Kernel 4.15
GPUs: 2 x VEGA, or 2 x gfx803
ROCm: 2.2
RCCL: 0.7.5(build `master` and installed it to `/opt/rocm/rccl`)

```
HIP version: 1.5.19055
HCC clang version 9.0.0 (/data/jenkins_workspace/compute-rocm-rel-2.2/external/hcc-tot/clang c792478f19beee13540053f188094898a008d245) (/data/jenkins_workspace/compute-rocm-rel-2.2/external/hcc-tot/compiler 22192ff6ed5120e2f4ec58a13049025537908ec3) (based on HCC 1.3.19092-1dcecff-c792478-22192ff )
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm/hcc/bin
```

```
========================        ROCm System Management Interface        ========================
================================================================================================
GPU   Temp   AvgPwr   SCLK    MCLK    PCLK           Fan     Perf    PwrCap   SCLK OD   MCLK OD  GPU%
0     75.0c  96.0W    1138Mhz 800Mhz  8.0GT/s, x16   32.94%  manual  100.0W   0%        0%       99%      
1     73.0c  98.0W    1138Mhz 800Mhz  8.0GT/s, x16   12.94%  manual  100.0W   0%        0%       100%     
================================================================================================
========================               End of ROCm SMI Log              ========================
```

Procedure is

```
$ /opt/rocm/hip/bin/hipcc -hc -I/opt/rocm/rccl/include allreduce.cpp -L/opt/rocm/lib -lrccl
$ ./a.out
Memory access fault by GPU node-1 (Agent handle: 0x1244a40) on address 0x7f365cc02000. Reason: Page not present or supervisor privilege.
Aborted (core dumped) 
```

**Comment by wenkaidu** [comment]
Please verify with latest RCCL

**Comment by syoyo** [comment]
It does not seg fault now, but still dont work. allreduce sample program will go into infinite loop at `rcclAllReduce`. 

4 x VEGAs, x299, Ubuntu 18.04.2

```
$ uname -a
4.15.0-48-generic #51-Ubuntu SMP Wed Apr 3 08:28:49 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

$ dkms status
amdgpu, 2.4-25, 4.15.0-48-generic, x86_64: installed
amdgpu, 2.4-25, 4.15.0-50-generic, x86_64: installed
```

```
[781376.268234] kfd2kgd: amdgpu_vm_bo_update failed
[781376.268236] kfd2kgd: update_gpuvm_pte() failed
[781376.268237] kfd2kgd: Failed to map bo to gpuvm
[781376.268238] Failed to map to gpu 0/3
[781376.268243] kfd2kgd: amdgpu_vm_bo_update failed
[781376.268245] kfd2kgd: update_gpuvm_pte() failed
[781376.268246] kfd2kgd: Failed to map bo to gpuvm
[781376.268247] Failed to map to gpu 0/3
[781376.268252] kfd2kgd: amdgpu_vm_bo_update failed
[781376.268253] kfd2kgd: update_gpuvm_pte() failed
[781376.268254] kfd2kgd: Failed to map bo to gpuvm
[781376.268256] Failed to map to gpu 0/3
```

**Comment by syoyo** [comment]
I have run it with old rccl build, since recent rccl https://github.com/ROCmSoftwarePlatform/rccl/commit/0d6a5a3d25895db5266ee2fd0dbbc5af81048844 failed to compile librccl(it looks newer HIP required. I'm using ROCm 2.4 apt version of HIP)

```
[ 22%] Building CXX object CMakeFiles/rccl.dir/src/collectives/device/reduce_scatter_0.cpp.o
/home/syoyo/work/rccl/build/src/transport/p2p.cpp:109:7: error: use of undeclared identifier 'hipExtGetLinkTypeAndHopCount'
  if (hipExtGetLinkTypeAndHopCount(myInfo->cudaDev, peerInfo->cudaDev, &link_type, &hops) != hipSuccess) {
      ^
1 error generated.
/home/syoyo/work/rccl/build/src/transport/p2p.cpp:109:7: error: use of undeclared identifier 'hipExtGetLinkTypeAndHopCount'
  if (hipExtGetLinkTypeAndHopCount(myInfo->cudaDev, peerInfo->cudaDev, &link_type, &hops) != hipSuccess) {
      ^
[ 25%] Building CXX object CMakeFiles/rccl.dir/src/collectives/device/reduce_scatter_1.cpp.o
```

**Comment by wenkaidu** [comment]
Please try build/test again as ROCm 2.5 has been released. In future, please use RCCL release branch that matches ROCm release in case of API changes.

**Comment by syoyo** [comment]
@wenkaidu I'm failing to build unit test(for building rccl sample program, since allreduce sample has been removed) due to the lack of OpenMP support in hcc.

```
$ ./install -t

-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
-- HIP compiler: hcc
-- HIP runtime: HCC
Going to build unit tests (Installed in /test/UnitTests)
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find OpenMP_CXX (missing: OpenMP_CXX_FLAGS OpenMP_CXX_LIB_NAMES)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.10/Modules/FindOpenMP.cmake:447 (find_package_handle_standard_args)
  test/CMakeLists.txt:14 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/syoyo/work/rccl/build/release/CMakeFiles/CMakeOutput.log".
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
-- HIP compiler: hcc
-- HIP runtime: HCC
Going to build unit tests (Installed in /test/UnitTests)
CMake Error at /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find OpenMP_CXX (missing: OpenMP_CXX_FLAGS OpenMP_CXX_LIB_NAMES)
Call Stack (most recent call first):
  /usr/share/cmake-3.10/Modules/FindPackageHandleStandardArgs.cmake:378 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.10/Modules/FindOpenMP.cmake:447 (find_package_handle_standard_args)
  test/CMakeLists.txt:14 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/syoyo/work/rccl/build/release/CMakeFiles/CMakeOutput.log".
Makefile:1270: recipe for target 'cmake_check_build_system' failed

$ hcc -v
HCC clang version 9.0.0 (/home/jenkins/jenkins-root/workspace/compute-rocm-rel-2.5/external/hcc-tot/clang 7c03a2e9172656a0832bdb8e0a0c9cd2cbf634a1) (/home/jenkins/jenkins-root/workspace/compute-rocm-rel-2.5/external/hcc-tot/compiler 04d27535fcc4ca8250eaa86e01883c43901cd9ac) (based on HCC 1.3.19212-ef84ec5-7c03a2e-04d2753 )
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /opt/rocm/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.4.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.4.0
Candidate multilib: .;@m64
Candidate multilib: 32;@m32
Candidate multilib: x32;@mx32
Selected multilib: .;@m64
Found HCC installation: /opt/rocm/bin/..
```

Although apt-installed hcc itself(clang?) supports OpenMP feature, but hcc distribution lacks `omp.h`. 

@wenkaidu Is recent hcc supports OpenMP? How do you build unit test?

**Comment by syoyo** [comment]
@wenkaidu I have ran `rcc-test` https://github.com/ROCmSoftwarePlatform/rccl-tests and it worked without segmentation fault.

```
$ LD_LIBRARY_PATH=/opt/rocm/rccl/lib ./all_gather_perf -g 4
# nThread 1 nGpus 4 minBytes 33554432 maxBytes 33554432 step: 1048576(bytes) warmup iters: 5 iters: 20 validation: 1 
#
# Using devices
#   Rank  0 Pid  23147 on        wwk device  0 [0x0c] Vega 10 XT [Radeon RX Vega 64]
#   Rank  1 Pid  23147 on        wwk device  1 [0x19] Vega 10 XT [Radeon RX Vega 64]
#   Rank  2 Pid  23147 on        wwk device  2 [0x67] Vega 10 XT [Radeon RX Vega 64]
#   Rank  3 Pid  23147 on        wwk device  3 [0x6a] Vega 10 XT [Radeon RX Vega 64]
#
#                                             out-of-place                       in-place          
#       size         count    type     time   algbw   busbw  error     time   algbw   busbw  error
#        (B)    (elements)             (us)  (GB/s)  (GB/s)            (us)  (GB/s)  (GB/s)       
    33554432       2097152   float    13115    1.92    1.92  0e+00    12802    1.97    1.97  0e+00
# Out of bounds values : 0 OK
# Avg bus bandwidth    : 1.94233 
```

**Comment by wenkaidu** [comment]
For building unit test, you need to remove temp build folder after installing libomp-dev.
You may add HSA_FORCE_FINE_GRAIN_PCIE=1 environment variable for better performance if the GPUs are peer to peer connected throughput PCIe, i.e. HSA_FORCE_FINE_GRAIN_PCIE=1 ./all_gather_perf -g 4

**Comment by syoyo** [comment]
@wenkaidu I see. I have installed llvm-8 and libomp8-dev. It looks hcc does not look into omp headers other than libomp-dev. Even though it would not be a recommended way, I have uninstalled llvm-8 and installing `libomp-dev` solved the situation.

> HSA_FORCE_FINE_GRAIN_PCIE=1

This didn't help for the performance. It still shows 1.97 GB/s.

Although VEGA system looks working, I found rccl still fails on 2 x gfx803 system.

```
$ HSA_FORCE_FINE_GRAIN_PCIE=1 build/release/test/UnitTests
Running main() from /home/syoyo/work/rccl/build/release/googletest-src/googletest/src/gtest_main.cc
[==========] Running 1632 tests from 7 test cases.
[----------] Global test environment set-up.
[----------] 192 tests from AllGatherCorrectnessSweep/AllGatherCorrectnessTest
[ RUN      ] AllGatherCorrectnessSweep/AllGatherCorrectnessTest.Correctness/0
Memory access fault by GPU node-1 (Agent handle: 0x1563ba0) on address (nil). Reason: Page not present or supervisor privilege.
Aborted (core dumped)

$ /opt/rocm/bin/rocminfo

=====================    
HSA System Attributes    
=====================    
Runtime Version:         1.1
System Timestamp Freq.:  1000.000000MHz
Sig. Max Wait Duration:  18446744073709551615 (number of timestamp)
Machine Model:           LARGE                              
System Endianness:       LITTLE                             

==========               
HSA Agents               
==========               
*******                  
Agent 1                  
*******                  
  Name:                    AMD Ryzen 7 2700X Eight-Core Processor
  Vendor Name:             CPU                                
  Feature:                 None specified                     
  Profile:                 FULL_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        0                                  
  Queue Min Size:          0                                  
  Queue Max Size:          0                                  
  Queue Type:              MULTI                              
  Node:                    0                                  
  Device Type:             CPU                                
  Cache Info:              
    L1:                      32768KB                            
  Chip ID:                 0                                  
  Cacheline Size:          64                                 
  Max Clock Frequency (MHz):3700                               
  BDFID:                   0                                  
  Compute Unit:            16                                 
  Features:                None
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: KERNARG, FINE GRAINED
      Size:                    16419820KB                         
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Acessible by all:        TRUE                               
    Pool 2                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    16419820KB                         
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Acessible by all:        TRUE                               
  ISA Info:                
    N/A                      
*******                  
Agent 2                  
*******                  
  Name:                    gfx803                             
  Vendor Name:             AMD                                
  Feature:                 KERNEL_DISPATCH                    
  Profile:                 BASE_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        128                                
  Queue Min Size:          4096                               
  Queue Max Size:          131072                             
  Queue Type:              MULTI                              
  Node:                    1                                  
  Device Type:             GPU                                
  Cache Info:              
    L1:                      16KB                               
  Chip ID:                 26591                              
  Cacheline Size:          64                                 
  Max Clock Frequency (MHz):1275                               
  BDFID:                   9728                               
  Compute Unit:            32                                 
  Features:                KERNEL_DISPATCH 
  Fast F16 Operation:      FALSE                              
  Wavefront Size:          64                                 
  Workgroup Max Size:      1024                               
  Workgroup Max Size Per Dimension:
    Dim[0]:                  67109888                           
    Dim[1]:                  637535232                          
    Dim[2]:                  0                                  
  Grid Max Size:           4294967295                         
  Waves Per CU:            40                                 
  Max Work-item Per CU:    2560                               
  Grid Max Size per Dimension:
    Dim[0]:                  4294967295                         
    Dim[1]:                  4294967295                         
    Dim[2]:                  4294967295                         
  Max number Of fbarriers Per Workgroup:32                                 
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    16777216KB                         
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Acessible by all:        FALSE                              
    Pool 2                   
      Segment:                 GROUP                              
      Size:                    64KB                               
      Allocatable:             FALSE                              
      Alloc Granule:           0KB                                
      Alloc Alignment:         0KB                                
      Acessible by all:        FALSE                              
  ISA Info:                
    ISA 1                    
      Name:                    amdgcn-amd-amdhsa--gfx803          
      Machine Models:          HSA_MACHINE_MODEL_LARGE            
      Profiles:                HSA_PROFILE_BASE                   
      Default Rounding Mode:   NEAR                               
      Default Rounding Mode:   NEAR                               
      Fast f16:                TRUE                               
      Workgroup Max Dimension: 
        Dim[0]:                  67109888                           
        Dim[1]:                  1024                               
        Dim[2]:                  16777217                           
      Workgroup Max Size:      1024                               
      Grid Max Dimension:      
        x                        4294967295                         
        y                        4294967295                         
        z                        4294967295                         
      Grid Max Size:           4294967295                         
      FBarrier Max Size:       32                                 
*******                  
Agent 3                  
*******                  
  Name:                    gfx803                             
  Vendor Name:             AMD                                
  Feature:                 KERNEL_DISPATCH                    
  Profile:                 BASE_PROFILE                       
  Float Round Mode:        NEAR                               
  Max Queue Number:        128                                
  Queue Min Size:          4096                               
  Queue Max Size:          131072                             
  Queue Type:              MULTI                              
  Node:                    2                                  
  Device Type:             GPU                                
  Cache Info:              
    L1:                      16KB                               
  Chip ID:                 26591                              
  Cacheline Size:          64                                 
  Max Clock Frequency (MHz):1130                               
  BDFID:                   9984                               
  Compute Unit:            32                                 
  Features:                KERNEL_DISPATCH 
  Fast F16 Operation:      FALSE                              
  Wavefront Size:          64                                 
  Workgroup Max Size:      1024                               
  Workgroup Max Size Per Dimension:
    Dim[0]:                  67109888                           
    Dim[1]:                  654312448                          
    Dim[2]:                  0                                  
  Grid Max Size:           4294967295                         
  Waves Per CU:            40                                 
  Max Work-item Per CU:    2560                               
  Grid Max Size per Dimension:
    Dim[0]:                  4294967295                         
    Dim[1]:                  4294967295                         
    Dim[2]:                  4294967295                         
  Max number Of fbarriers Per Workgroup:32                                 
  Pool Info:               
    Pool 1                   
      Segment:                 GLOBAL; FLAGS: COARSE GRAINED      
      Size:                    8388608KB                          
      Allocatable:             TRUE                               
      Alloc Granule:           4KB                                
      Alloc Alignment:         4KB                                
      Acessible by all:        FALSE                              
    Pool 2                   
      Segment:                 GROUP                              
      Size:                    64KB                               
      Allocatable:             FALSE                              
      Alloc Granule:           0KB                                
      Alloc Alignment:         0KB                                
      Acessible by all:        FALSE                              
  ISA Info:                
    ISA 1                    
      Name:                    amdgcn-amd-amdhsa--gfx803          
      Machine Models:          HSA_MACHINE_MODEL_LARGE            
      Profiles:                HSA_PROFILE_BASE                   
      Default Rounding Mode:   NEAR                               
      Default Rounding Mode:   NEAR                               
      Fast f16:                TRUE                               
      Workgroup Max Dimension: 
        Dim[0]:                  67109888                           
        Dim[1]:                  1024                               
        Dim[2]:                  16777217                           
      Workgroup Max Size:      1024                               
      Grid Max Dimension:      
        x                        4294967295                         
        y                        4294967295                         
        z                        4294967295                         
      Grid Max Size:           4294967295                         
      FBarrier Max Size:       32                                 
*** Done ***       
```

**Comment by wenkaidu** [comment]
Can you please collect a few logs with NCCL_DEBUG=INFO?
On both VEGA and gfx803, please collect logs with and without HSA_FORCE_FINE_GRAIN_PCIE=1 while running rccl-tests. So we will have total 4 logs.

On gfx803, can you use "lspci -v -d:1002:66a1" and share output? Please replace 1002:66a1 to your gfx803 VID:PID.

**Comment by syoyo** [comment]
I will try to run tests with `NCC_DEBUG` and `HSA_FORCE_FINE_GRAIN_PCIE` later.

> On gfx803, can you use "lspci -v -d:1002:66a1" and share output? Please replace 1002:66a1 to your gfx803 VID:PID.

For some reason, it does not print anything.

```
26:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X] [1002:67df] (rev ef) (prog-if 00 [VGA controller])
27:00.0 VGA compatible controller [0300]: Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X] [1002:67df] (rev cf) (prog-if 00 [VGA controller])
syoyo@e5:~$ lspci -v -d:1002:67df
$ 
```

On the contrary, VAGA system shows something

```
$ lspci -v -d 1002:687f
0c:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Vega 10 XT [Radeon RX Vega 64] (rev c3) (prog-if 00 [VGA controller])
	Subsystem: XFX Pine Group Inc. Vega 10 XT [Radeon RX Vega 64]
	Flags: bus master, fast devsel, latency 0, IRQ 85, NUMA node 0
	Memory at 380000000000 (64-bit, prefetchable) [size=8G]
	Memory at 380200000000 (64-bit, prefetchable) [size=2M]
	I/O ports at 4000 [size=256]
	Memory at 80500000 (32-bit, non-prefetchable) [size=512K]
	Expansion ROM at 80580000 [disabled] [size=128K]
	Capabilities: <access denied>
	Kernel driver in use: amdgpu
	Kernel modules: amdgpu

19:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Vega 10 XT [Radeon RX Vega 64] (rev c0) (prog-if 00 [VGA controller])
	Subsystem: Advanced Micro Devices, Inc. [AMD/ATI] Vega 10 XT [Radeon RX Vega 64]
	Flags: bus master, fast devsel, latency 0, IRQ 86, NUMA node 0
	Memory at 381000000000 (64-bit, prefetchable) [size=8G]
	Memory at 381200000000 (64-bit, prefetchable) [size=2M]
	I/O ports at 7000 [size=256]
	Memory at a0500000 (32-bit, non-prefetchable) [size=512K]
	Expansion ROM at a0580000 [disabled] [size=128K]
	Capabilities: <access denied>
	Kernel driver in use: amdgpu
	Kernel modules: amdgpu

67:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Vega 10 XT [Radeon RX Vega 64] (rev c3) (prog-if 00 [VGA controller])
	Subsystem: XFX Pine Group Inc. Vega 10 XT [Radeon RX Vega 64]
	Flags: bus master, fast devsel, latency 0, IRQ 87, NUMA node 0
	Memory at 382000000000 (64-bit, prefetchable) [size=8G]
	Memory at 382200000000 (64-bit, prefetchable) [size=2M]
	I/O ports at b000 [size=256]
	Memory at e0900000 (32-bit, non-prefetchable) [size=512K]
	Expansion ROM at e0980000 [disabled] [size=128K]
	Capabilities: <access denied>
	Kernel driver in use: amdgpu
	Kernel modules: amdgpu

6a:00.0 VGA compatible controller: Advanced Micro Devices, Inc. [AMD/ATI] Vega 10 XT [Radeon RX Vega 64] (rev c1) (prog-if 00 [VGA controller])
	Subsystem: Advanced Micro Devices, Inc. [AMD/ATI] Vega 10 XT [Radeon RX Vega 64]
	Flags: bus master, fast devsel, latency 0, IRQ 88, NUMA node 0
	Memory at 382400000000 (64-bit, prefetchable) [size=8G]
	Memory at 382300000000 (64-bit, prefetchable) [size=2M]
	I/O ports at a000 [size=256]
	Memory at e0700000 (32-bit, non-prefetchable) [size=512K]
	Expansion ROM at 000c0000 [disabled] [size=128K]
	Capabilities: <access denied>
	Kernel driver in use: amdgpu
	Kernel modules: amdgpu
```

**Comment by syoyo** [comment]
@wenkaidu 

> Can you please collect a few logs with NCCL_DEBUG=INFO?
> On both VEGA and gfx803, please collect logs with and without HSA_FORCE_FINE_GRAIN_PCIE=1 while running rccl-tests. So we will have total 4 logs.

Created separate issue for it : https://github.com/ROCmSoftwarePlatform/rccl/issues/80

**Comment by wenkaidu** [comment]
Do you have further questions, or are you OK closing this issue? Thanks

**Comment by syoyo** [comment]
@wenkaidu Segfault issue still exists for 2 x gfx803 system configuration. Do you know gfx803 is supported in RCCL?

**Comment by wenkaidu** [comment]
I have not personally tested on gfx803 machines. Can you run rccl-tests on it with NCCL_DEBUG=INFO and share the log?

**Comment by syoyo** [comment]
There has been advances in ROCm and RCCL, and allreduce.cpp file has gone in the repo. 

At least I could confirm UnitTests runs well on ROCm 3.3 + x299 + 4 VEGAs(3 VEGA10 + 1 VEGA20),  so close the issue.
